### ISSUE TITLE
[Android]Add sdk_rpc_request event to Android SDK when dapp triggers an RPC method

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-android-sdk#101]
### Task

1. Add the following events to the Android SDK
sdk_rpc_request
2. sdk_rpc_request should be fired when dapp calls ONLY the RPC method invoked by a dapp through the SDK that require wallet confirmation (check the google sheet)
3. Both events should contain under "properties":
- rpc method name
- dapp metadata(title, url, source, sdkversion, platform, channel id(user id), timestamp)

### Acceptance Criteria
- [ ] Events should be added and fired correctly
- [ ] Events have the right format and should have additional info under "properties" for the correct mixpanel mapping.
- [ ] Unit tests should be added on the mobile app to check whether they are triggered correctly.
- [ ] QA should be done with Segment and Mixpanel to confirm if the events are fired correctly, received correctly on segment and mapped correctly on mixpanel
